INSERT INTO games (name) VALUES
  ('General'),
  ('Guilty Gear Xrd: Rev2'),
  ('Tekken 7'),
  ('Dragonball FighterZ'),
  ('Blazblue: Central Fiction');

INSERT INTO chars (name, game_id) VALUES
  ('General',1);

INSERT INTO chars (name, game_id) VALUES
    ('General',2),
    ('Answer',2),
    ('Axl',2),
    ('Baiken',2),
    ('Bedman',2),
    ('Chipp',2),
    ('Dizzy',2),
    ('Elphelt',2),
    ('Faust',2),
    ('I-No',2),
    ('Jack-O',2),
    ('Jam',2),
    ('Johnny',2),
    ('Kum',2),
    ('Ky',2),
    ('Leo',2),
    ('May',2),
    ('Millia',2),
    ('Potemkin',2),
    ('Ramlethal',2),
    ('Raven',2),
    ('Sin',2),
    ('Slayer',2),
    ('Sol',2),
    ('Venom',2),
    ('Zato-1',2);

INSERT INTO chars (name, game_id) VALUES
    ('General',3),
    ('Akuma',3),
    ('Alisa',3),
    ('Asuka',3),
    ('Bob',3),
    ('Claudio',3),
    ('Devil Jin',3),
    ('Dragunov',3),
    ('Eddy ',3),
    ('Eliza',3),
    ('Feng',3),
    ('Geese',3),
    ('Gigas',3),
    ('Heihachi',3),
    ('Hwoarang',3),
    ('Jack-7',3),
    ('Jin',3),
    ('Josie ',3),
    ('Katarina',3),
    ('King',3),
    ('Kazuya',3),
    ('Kazumi',3),
    ('Kuma',3),
    ('Lars',3),
    ('Lee',3),
    ('Lili ',3),
    ('Leo',3),
    ('Lucky Chloe',3),
    ('Law',3),
    ('Master Raven',3),
    ('Miguel',3),
    ('Nina',3),
    ('Paul',3),
    ('Panda ',3),
    ('Shaheen',3),
    ('Steve',3),
    ('Xiaoyu',3),
    ('Yoshimitsu ',3);

INSERT INTO chars (name, game_id) VALUES
    ('General',4),
    ('Android 16',4),
    ('Android 18',4),
    ('Android 21',4),
    ('Beerus',4),
    ('Ginyu',4),
    ('Cell',4),
    ('Frieza',4),
    ('Gohan (Adult)',4),
    ('Gohan (Teen)',4),
    ('Goku (SSB)',4),
    ('Goku (SSJ)',4),
    ('Goku Black',4),
    ('Gotenks',4),
    ('Hit',4),
    ('Piccolo',4),
    ('Kid Buu',4),
    ('Krillin',4),
    ('Majin Buu',4),
    ('Nappa',4),
    ('Tien',4),
    ('Trunks',4),
    ('Vegeta (SSJ)',4),
    ('Vegeta (SSB)',4),
    ('Yamcha',4);

INSERT INTO chars (name, game_id) VALUES
    ('General',5),
    ('Amane',5),
    ('Arakune',5),
    ('Azrael',5),
    ('Bang',5),
    ('Bullet',5),
    ('Carl',5),
    ('Celica',5),
    ('Es',5),
    ('Hakumen',5),
    ('Hazama',5),
    ('Hibiki',5),
    ('Tager',5),
    ('Izanami',5),
    ('Izayoi',5),
    ('Jin',5),
    ('Jubei',5),
    ('Kagura',5),
    ('Kokonoe',5),
    ('Litchi',5),
    ('Mai',5),
    ('Makoto',5),
    ('Naoto',5),
    ('Nine',5),
    ('Noel',5),
    ('Platinum',5),
    ('Rachel',5),
    ('Ragna',5),
    ('Relius',5),
    ('Susanoo',5),
    ('Taokaka',5),
    ('Tsubaki',5),
    ('Valkenhayn',5),
    ('Yuuki',5),
    ('Λ-11',5),
    ('μ-12',5),
    ('ν-13',5);

INSERT INTO categories (name) VALUES
  ('General'),
  ('Combo'),
  ('Okizeme'),
  ('Guide'),
  ('MU'),
  ('Misc.');

INSERT INTO posts (title, description,  game_id, char_id) VALUES
  ('Sol BNBs', 'List of bnbs', 2, 25),
  ('Sol Framedata','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque vitae sodales risus. Aliquam ac porttitor lectus, pharetra molestie urna. Donec pellentesque maximus aliquet. Phasellus consectetur volutpat mattis. Aliquam lacinia, massa quis iaculis sagittis, diam odio pulvinar augue, eu tristique tellus velit ut risus. Mauris placerat imperdiet tincidunt. Duis ornare finibus neque, eget rhoncus justo facilisis at. Nulla efficitur auctor metus, sit amet sollicitudin odio pharetra a. Sed sodales tristique mi, eget accumsan risus lobortis id. Sed pulvinar libero ex, sit amet consectetur erat consectetur eget. Phasellus ullamcorper magna non diam congue sodales. Nullam eu mi fermentum, pretium odio vitae, gravida eros. Suspendisse malesuada sem nisl, eu accumsan velit posuere in. Curabitur nec urna volutpat, tempor ante facilisis, scelerisque purus. Vivamus in nisl ut velit mollis gravida.Suspendisse turpis turpis, condimentum in dui a, dictum porttitor velit. Maecenas posuere tortor eget tempus pellentesque. Pellentesque tempor eros ut auctor ultrices. Ut nec est ac elit vulputate imperdiet. Pellentesque eleifend consequat turpis ut vulputate. Donec magna nulla, tempor sed placerat ac, efficitur et nunc. Mauris hendrerit rutrum congue. Quisque eros sapien, laoreet eu imperdiet ut, lacinia non urna. Duis consequat eros ut lacus fringilla eleifend. Sed dui risus, facilisis a sodales sed, maximus vitae velit. Nam aliquam diam at ex mattis, quis blandit libero luctus cras amet. ', 2, 25),
  ('Feng BNBs','blabla' ||
               'blabli' ||
               'blibla' ||
               'hehehhe', 3, 38),
  ('Tsubaki BNBs','test\nhueuiad\nduiygsqudq\ndusqhidisq', 5, 122);

INSERT INTO cats (post_id, category_id) VALUES
  (1,2),
  (2,6),
  (3,2),
  (4,2);

INSERT INTO links (url, post_id) VALUES
  ('http://www.dustloop.com/wiki/index.php/GGXRD/Sol_Badguy/Combos', 1),
  ('http://www.dustloop.com/wiki/index.php/GGXRD-R2/Sol_Badguy/Combos', 1),
  ('http://www.dustloop.com/wiki/index.php?title=GGXRD-R2/Sol_Badguy/Frame_Data', 2),
  ('http://alphabla.de/ggxrd/index.php?id=14',2),
  ('http://forums.tekkengamer.com/viewtopic.php?f=4&t=146',3),
  ('http://www.evernote.com/l/AZZj8QupdRNLWZayTqsNqTuLGfkyO1LWzA4/',4)