version: '2.1'

services:
  nginx:
    image: fholzer/nginx-brotli
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
      - /etc/letsencrypt:/etc/nginx/certs
      - "../frontend/dist:/usr/share/nginx/html"
    depends_on:
      - gunicorn
    restart: always  
  postgres:
    image: postgres:10-alpine
    env_file: ./postgres/.env
    volumes:
      - "/home/fgld/dumps:/usr/share/dumps"
    restart: always  
  gunicorn:
    build: ../backend
    env_file: ./gunicorn/.env
    expose:
      - "8000"
    depends_on: 
      - postgres
    restart: always
